import pathway360logo from "./assets/pathway360logo.png";
import introimg from "./assets/intro-img.jpg";
import gallery1 from "./assets/gallery/gallery-1.jpeg"
import gallery2 from "./assets/gallery/gallery-2.jpeg"
import gallery3 from "./assets/gallery/gallery-3.jpeg"
import gallery4 from "./assets/gallery/gallery-4.jpeg"
import gallery5 from "./assets/gallery/gallery-5.jpeg"
import gallery6 from "./assets/gallery/gallery-6.jpeg"
import gallery7 from "./assets/gallery/gallery-7.jpeg"
import gallery8 from "./assets/gallery/gallery-8.jpeg"
import gallery9 from "./assets/gallery/gallery-9.jpeg"
import gallery10 from "./assets/gallery/gallery-10.jpeg"
import gallery11 from "./assets/gallery/gallery-11.jpeg"
import gallery12 from "./assets/gallery/gallery-12.jpeg"
import gallery13 from "./assets/gallery/gallery-13.jpeg"
import gallery14 from "./assets/gallery/gallery-14.jpeg"
import gallery15 from "./assets/gallery/gallery-15.jpeg"
import gallery16 from "./assets/gallery/gallery-16.jpeg"
import gallery17 from "./assets/gallery/gallery-17.jpeg"
import gallery18 from "./assets/gallery/gallery-18.jpeg"
import gallery19 from "./assets/gallery/gallery-19.jpeg"
import gallery20 from "./assets/gallery/gallery-20.jpg"
import sendachild from "./assets/programs/sendachildtoschool.jpg"

export  {pathway360logo, introimg, gallery1, gallery2, gallery3, gallery4, gallery5, gallery6, gallery7, gallery8, gallery9, gallery10, gallery11, gallery12, gallery13, gallery14, gallery15,gallery16, gallery17, gallery18, gallery19, gallery20,  sendachild};
